include:
  - .well-known

page_title                                : House Manager

ios_app_id                                : 6569254568
ios_app_country                           : us

appstore_link                             : https://apps.apple.com/app/apple-store/id6569254568
privacy_policy_link                       : https://house-app.com/policies
blog_link                                 : https://blog.house-app.com
presskit_download_link                    : assets/House_Manager_Press_Kit.zip

app_icon                                  : assets/appicon.png
app_name                                  : House Manager
app_price                                 : Free
app_description                           : House Manager is an app for iOS & macOS designed to be your home's command center, keeping every detail at your fingertips. Save time, prevent costly repairs, and protect your investment!

enable_smart_app_banner                   : true

your_name                                 : Shayes Apps
your_link                                 : https://www.shayesapps.com
email_address                             : support@shayesapps.com
facebook_username                         : shayesapps
instagram_username                        : shayesapps
mastodon_link                             : https://indieapps.space/@shayesapps

features                                  :

  - title                                 : Beautiful Design
    description                           : Intuitive layout puts everything right at your fingertips
    fontawesome_icon_name                 : palette

  - title                                 : Inventory
    description                           : Track all your home appliances in one place
    fontawesome_icon_name                 : list

  - title                                 : Maintenance
    description                           : Smart reminders for routine maintenance tasks
    fontawesome_icon_name                 : magic

  - title                                 : Projects
    description                           : Organize home improvement projects
    fontawesome_icon_name                 : home

  - title                                 : Paints
    description                           : Track paint colors & finishes for each room
    fontawesome_icon_name                 : paint-roller

  - title                                 : Attachments
    description                           : Keep links, files, & photos with your inventory items
    fontawesome_icon_name                 : link

  - title                                 : History
    description                           : Keep a log of all your home's maintenance
    fontawesome_icon_name                 : history

  - title                                 : Reports
    description                           : Create PDF reports for your inventory, paints, and projects
    fontawesome_icon_name                 : file-pdf

  - title                                 : Home Sharing
    description                           : Share your home with a partner or roommate.
    fontawesome_icon_name                 : users

  - title                                 : Multiple Device Support
    description                           : Available for iOS, iPadOS, & macOS devices with seamless syncing
    fontawesome_icon_name                 : sync

# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
